USE master;
GO

IF EXISTS (SELECT * FROM sys.databases WHERE name = 'HotelManagement')
BEGIN
	DROP DATABASE HotelManagement;
END
GO

CREATE DATABASE HotelManagement;
GO

USE HotelManagement;

CREATE TABLE CUSTOMER
(
	Id INT PRIMARY KEY,
	FullName NVARCHAR(50) NOT NULL,
	Telephone NVARCHAR(12),
	Email NVARCHAR(50) NOT NULL,
	Birthday DATETIME2,
	-- 0: active -- 1: deleted
	[Status] BIT DEFAULT 0,
	[Password] NVARCHAR(50) NOT NULL
)
GO

CREATE TABLE ROOM_TYPE
(
	Id INT PRIMARY KEY,
	[Name] NVARCHAR(50) NOT NULL,
	[Description] NVARCHAR(220),
	Note NVARCHAR(220)
)
GO

CREATE TABLE ROOM
(
	Id INT PRIMARY KEY,
	Number INT NOT NULL,
	[Description] NVARCHAR(220),
	MaxCapacity INT NOT NULL,
	-- 0: active -- 1: deleted
	[Status] BIT DEFAULT 0,
	PricePerDate DECIMAL NOT NULL,
	TypeId INT FOREIGN KEY REFERENCES ROOM_TYPE(ID)
)
GO

CREATE TABLE RESERVATION
(
	Id INT PRIMARY KEY,
	OnDate DATETIME2 NOT NULL,
	RoomId INT FOREIGN KEY REFERENCES ROOM(ID),
	CustomerId INT FOREIGN KEY REFERENCES CUSTOMER(ID),
	-- STATUS PENDING -> CONFIRMED -> DONE
	--							   -> CANCELLED
	[Status] NVARCHAR(10) NOT NULL DEFAULT 'PENDING'
)
GO